spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/postgres
    driver-class-name:  org.postgresql.Driver
    username:  postgres
    password:  123456
mybatis:
  mapper-locations: classpath:mapper/*
